### ISSUE TITLE
Devolucion a proveedor de bodega

### ISSUE THREAD

**Issue by ErickVAleman** [sounix/ControlCasos#13]
Se comunico berta (bodega) con nosotros con la peticion de realizar un ajuste de entrada ya que se realizo una devolucion a proveedor pero este le dijo que no lo descontaran de la factura que solo le haria el cambio fisico del producto.

**Comment by ErickVAleman** [comment]
10:37 AM -- En la devolución se regresaron 50 kg de frijol y el proveedor los repuso con frijol schetino de 900, se le comento a bertha (bodega) que lo recibiera y le diera entrada con el costo del sistema

**Comment by sounix** [comment]
Ya se completo todo el proceso confirmado por erick por lo que damos por cerrado este caso
