### ISSUE TITLE
Problemas de Impresora Oluta 

### ISSUE THREAD

**Issue by LMVP** [sounix/ControlCasos#15]
![whatsapp image 2018-09-27 at 12 11 05 pm](https://user-images.githubusercontent.com/36741980/46163644-5c364480-c251-11e8-9eaf-d2658b32b006.jpeg)

posible Error de toner Aunque el error hace Referencia a la lectura del chip de Cartucho de toner

**Comment by sounix** [comment]
Enterado hay que ver si es el caso lo comentas por favor.

**Comment by LMVP** [comment]
**corregido error en magnetico remplazo de pieza** 

![09b51e95-3a11-4e76-b696-e6901865316b](https://user-images.githubusercontent.com/36741980/46181668-c91b0000-c28c-11e8-80d8-0334c11039f4.jpg)
![d0dd6c96-483f-49d2-a9e2-284b1a3f5a3e](https://user-images.githubusercontent.com/36741980/46181669-c91b0000-c28c-11e8-92b4-d21432c39cf6.jpg)

**Comment by LMVP** [comment]
segunda incidencia reportan que esta atorando las hojas **el motivo es el atasco de una hoja en en el área del fusor
![ff936bb8-5cc7-4605-a868-3cc31beacca6](https://user-images.githubusercontent.com/36741980/46181714-05e6f700-c28d-11e8-9f84-7ccdbae7a85f.jpg)

despues de ello se hicieron pruebas de impresion por el personal a cargo
**

**Comment by sounix** [comment]
Caso cerrado con exito
