### ISSUE TITLE
Recuperacion de Video Golpe Auto Alejandro

### ISSUE THREAD

**Issue by sounix** [sounix/ControlCasos#16]
Ha que recuperar y respaldar el video del golpe al auto de alejandro la camara externa del super zaragoza el dia Jueves 27/09/2018 Evento 13:36

**Comment by sounix** [comment]
hay que convertir el archivo Channel06_20180927133559 que sea compatible con celulares

**Comment by LMVP** [comment]
archivo convertido Channel06_20180927133559_Convert alojado en 192.168.1.63/workflow

**Comment by LMVP** [comment]
video convertido y enviado por whatsapp de acuerdo a lo requerido

**Comment by sounix** [comment]
Listo gracias ya también lo envie al whatsapp del Contador Alejandro.
