### ISSUE TITLE
Mantenimiento a LOG de las DB

### ISSUE THREAD

**Issue by sounix** [sounix/ControlCasos#18]
Realizar hoy recorte de log a todas las bases de datos

**Comment by ErickVAleman** [comment]
## Estado en el que quedaron las bases de datos
##### 28/09/2018
| name            | FileSizeInMB  |	EmptySpaceInMB  |
|:---------------|:-------------:|:---------------:|
| SPABODEGA_DATA  | 361.062500    |	7.250000        |
| SPABODEGA_LOG   |	10.171875     |	9.195313        |
| SPACENTRO_DATA	| 519.500000	  | 0.312500        |
| SPACENTRO_LOG	  | 10.250000	    | 9.781250        |
| SPAJALTIPAN_DATA| 469.250000	  | 0.000000        |
| SPAJALTIPAN_LOG	| 11.500000	    | 11.070313       |
| SPAOLUTA_DATA	  | 496.437500	  | 0.437500        |
| SPAOLUTA_LOG	  | 22.000000	    | 0.476563        |
| SPASUPER1_DATA	| 372.375000	  | 0.437500        |
| SPASUPER1_LOG	  | 10.171875     | 8.156250        | 

###### No me tocaba a mi pero lo hice

**Comment by sounix** [comment]
Gracias por el aporte esta tarea debemos de fijarla para realizar la por lo menos dos días antes de cada fin de mes.
