### ISSUE TITLE
Omisión de reporteria por parte de Multirecargas

### ISSUE THREAD

**Issue by LMVP** [sounix/ControlCasos#28]
El dia viernes 31 de septiembre se le hizo saber a Multirecargas ahora SALDOPAGO que no habia llegado el detallado de recargas que consume cada sucursal y mencionaron que a las 3:30 de mismo dia estaria en el correo y harian una llamada para corroborar la informacion, de igual forma el dia sabado se hicieron las llamadas pértinentes pero nunca entro la llamada

**Comment by LMVP** [comment]
Se recibio llamada de Saldo Pago de parte del administrativo Alonso que sera hasta el dia miercoles del mes en curso que se hara llegar el reporte de venta tanto de las fechas 19/09/2018 al 25/09/2018 y 26/09/2018 al 02/10/2018 hasta entonces no habra corte con en el servicio

**Comment by sounix** [comment]
Ya llego el reporte de esta marca
