### ISSUE TITLE
Ayuda con Recuperacion de la Base de datos CAASA Acayucan

### ISSUE THREAD

**Issue by sounix** [sounix/ControlCasos#31]

**Comment by ErickVAleman** [comment]
# Recuperacion de base de datos en CAASA Acayucan
##### by ErickVAleman

Para manejar el fallo de base de datos en CAASA el ing Aldrin opto por establecer la base de datos en modo EMERGENCY y poder leer la base de datos y poder rescatar precios y costos, después de esto a la hora de la comida se me llamo ami para que asistiera a CAASA Acayucan para poder ayudar con el problema de su base de datos al principio estaba apoyando al ingeniero con las consultas para mudar los precios y costos, pero después de esto ejecute una consulta en la base de datos dañada para poder analizar el error y poder buscar una solución a partir de esto, leyendo un poco se opto por correr una consulta que solucionaria el error de dicha base de datos y la volveria a poner en forma.

```SQL
USE [master]
GO
ALTER DATABASE [TUDB] SET EMERGENCY
GO
DBCC CHECKDB('TUDB')
GO
ALTER DATABASE [TUDB] SET SINGLE_USER
GO
DBCC CHECKDB('TUDB',REPAIR_ALLOW_DATA_LOSS)
GO
ALTER DATABASE [TUDB] SET MULTI_USER
GO
ALTER DATABASE [TUDB] SET ONLINE
GO
```
###### Como recomendacion no correr todo a lo loco, usar el cerebro es gratis.

**Comment by sounix** [comment]
Recuperacion con exito al 100%
