### ISSUE TITLE
Problemas Checador de Asistencias Suc Victoria

### ISSUE THREAD

**Issue by sounix** [sounix/ControlCasos#34]
Por medio de correo electronico nos dicen que hay problemas con el checador hay que asistir a revisar.

**Comment by LMVP** [comment]
El error se debio a que el conector del dispositivo se movio del puerto usb por lo tanto se desconecto y no encendia el lector por lo que se cambio de puerto y encendio posterior a ello se corroboro su funcionamiento con la lectura de huellas siendo esta satisfactoria por el personal  a cargo

**Comment by sounix** [comment]
soporte exitoso
