### ISSUE TITLE
Ajustes de Existencias por Error de Compra en Bodega

### ISSUE THREAD

**Issue by ErickVAleman** [sounix/ControlCasos#39]
Hoy bodega comento que tenia un error de existencia en el articulo 0849261 ya que se equivocaron en ingresar la compra

**Comment by ErickVAleman** [comment]
El siguiente es el mensaje que bodega comunico

> Erick Buen día, soy Bertha
necesito
un favor, lo que pasa es que se le dio mal la entrada a la nido kinder 2.5 en la compra de Sams
se le dio entrada como nido Clásica
pero como la compra fue del 14 de septiembre, creo yo que no se puede cancelar la compra
lo correcto seria hacer un ajuste de salida y uno de entrada para corregir la partida,
solicito hacer el proceso de corrección por favor

justo después menciono los artículos cuales eran 
> se le dio entrada como nido clásica 2.52 kg este es el código 0849220
> 0849261 Leche Nido Kinder 1+ 2.5kg este es el correcto
Se le dio entrada a 11 pz
lo que pasa que doña carmen se equivoco al capturar la compra

**Comment by ErickVAleman** [comment]
Ya se ha resuelto el problema y se ha cancelado la compra y los costos que cambiaron se actualizaron pero se volvieron a cambiar a como los teníamos.

**Comment by ErickVAleman** [comment]
ya se puede cerrar la incidencia

**Comment by sounix** [comment]
Gracias por tus comentarios y queda cerrado con exito
