### ISSUE TITLE
Problemas con Camaras SPAVICTORIA

### ISSUE THREAD

**Issue by LMVP** [sounix/ControlCasos#40]
se reporto que no se estaba visualizando la camara que apunta hacia la bodega por lo que se reviso solo fue encontrada una aterrizacion en el polo positivo de la corriente que alimentaba dicha camara siendo un problema menor quedo resuelto

**Comment by LMVP** [comment]
también se explico la posibilidad de ver solo 2 camaras a lo ancho de la pantalla esa vista no esta disponible para el dvr por lo que se les dio la alternativa que cumplia con la necesidad

**Comment by sounix** [comment]
Resuelto con Exito
