### ISSUE TITLE
Ajustes de Existencia por fallo en Consolidacion

### ISSUE THREAD

**Issue by LMVP** [sounix/ControlCasos#46]
Hablo sucursal victoria solicitando el ajuste de salida por mercancia que habia consolidado spajaltipan que en su momento habian problemas tecnicos ya resueltos

Es muy importante ante estos eventos se traten como COMPRAS no como ajustes de entradas ya que con este no obtienes el costo y se omite el reporte de costeo de transferencias

**Comment by sounix** [comment]
Gracias por la observación es muy cierto y a partir de ahora así lo comunicaremos a todos en las tiendas
