### ISSUE TITLE
Asistir a Victoria - Revisar Problemas de Internet y Checador de Asistencia

### ISSUE THREAD

**Issue by sounix** [sounix/ControlCasos#48]

**Comment by LMVP** [comment]
Reportaron problema con bitácora de folios y revisando solo pusieron una cantidad X para apartar el folio siendo una cantidad mayor a 2000 .

problemas con el servicio de Internet ninguno encontrado esto va del lado del proveedor TELMEX al tener mucha latencia en la señal.

problemas con el lector de huellas.

argumentaron lo siguiente a las 7:30 que llegamos no servia y a las 9 ya empezó a funcionar al momento de la revisión no se encontró problemas con el lector

**Comment by sounix** [comment]
gracias por los comentarios doy por cerrado esta incidencia?

**Comment by ErickVAleman** [comment]
si
