### ISSUE TITLE
Cancelacion de factura en Bodega

### ISSUE THREAD

**Issue by ErickVAleman** [sounix/ControlCasos#49]
Se comunico bodega conmigo(@ErickVAleman) para tratar asuntos con una compra y lo que me dijo fue lo sig.
> no soy yo, Bertha
lo que pasa es que el 21 de sept capture una compra de Herdez
la cancele porque doña carmen me dijo que le aplicara un descuento
y ahora me habla para decirme que la cancele otra vez por que el descuento siempre no se va aplicar por que ya se la aplicaron a otra factura

Se procederá a reingresar la factura y a su cancelación y se vera que no se afecten los costos de artículos que hayan entrado recientemente

**Comment by sounix** [comment]
OK COMENTALO CON DOÑA IRMA PARA QUE VEA ESO DE LOS DESCUENTOS YA QUE NO FALTA MUCHO APRA PAGARSE, ANTES DE QUE LO HAGAN PLATICALE EL CASO PARA QUE ESTE AVISADA

**Comment by ErickVAleman** [comment]
Okey procedere a informale de dicha compra

**Comment by ErickVAleman** [comment]
Solicite el documento de la compra y esto fue lo que bodega me respondio
> BODEGA [10:11]
Si claro de hecho ya le marque antes de hablar con usted

**Comment by ErickVAleman** [comment]
#### Listo
Se le acaba de comunicar a doña Irma dicha operación.

**Comment by ErickVAleman** [comment]
#### Fin
Se ha procedido a realizar la cancelación.

**Comment by sounix** [comment]
GRACIAS POR LOS COMENTARIOS YA DOY POR TERMINADO ESTA INCIDENCIA
