### ISSUE TITLE
Ofertas Fin Semana 29 SEP - 01 OCT

### ISSUE THREAD

**Issue by sounix** [sounix/ControlCasos#5]

**Comment by JMelesio** [comment]
Se recibieron los archivos con el consentrado de ofertas para fin de semana de todas las tiendas, algunas muy desfasadas de timpo.
sucursal                     fecha y hora
zaragoza-----------Martes 25-09-18 a las 13:50
victoria-------------Martes 25-09-18 a las 20:13
oluta---------------Lunes 24-09-18 a las 15:5
jaltipan------------Martes 25-09-18 12:00 
carmen luz--------Jueves 27-09-18  12:04

**Comment by sounix** [comment]
Se envió a Imprenta
