### ISSUE TITLE
Falla al enfriar lácteos en Suc Jaltipan

### ISSUE THREAD

**Issue by sounix** [sounix/ControlCasos#50]
Reportó por medio de llamada el Sr Héctor que no está enfriando el mueble de lácteos y qué hay mucho producto

Se habló con él Tecnico y quedó de presentarse de 1 a 2 de la tarde en la sucursal

**Comment by JMelesio** [comment]
se reporta que el problema del equipo de lácteo ya está corregido y que ya está en producción

**Comment by JMelesio** [comment]
favor de cerrar el caso

**Comment by JMelesio** [comment]
El problema que presento el refrigerador de lácteo fue debido a que 3 de los ventiladores se quemaron, este problema se solucionó haciendo el cambio de motores de dichos ventiladores, los motores nuevos son de mejor calidad ya que son de balero.
