### ISSUE TITLE
Cotización 2018 0925

### ISSUE THREAD

**Issue by sounix** [sounix/ControlCasos#6]

**Comment by sounix** [comment]
ya se genero el pedido de cotización **Pedido 20180926-154**, quedo a la espera de la analitica.

> La sucursal de Oluta mando el pedido desde la semana pasada, hay que enviar un mail o hablar para comentar que es cada 15 dias y tocaba esta semana y no la pasada.

**Comment by ErickVAleman** [comment]
### Cotización Realizada
Se realizo la cotización con éxito y se envió a los medios correspondientes a través de correo electrónico 👍

**Comment by sounix** [comment]
Gracias por la información ya valide que fue recibida.
